import React, { useState, useEffect } from 'react';
import { Modal, Form, Input, InputNumber, Select, TimePicker, Typography, Row, Col, Divider, Card, Tag, Checkbox, Alert } from 'antd';
import { FieldGroupFormData } from '@/types/field.type';
import { SURFACE_TYPES, DIMENSIONS, DEFAULT_PRICING, COMPATIBLE_SPORT_GROUPS } from '@/mocks/default/defaultData';
import { Sport } from '@/types/sport.type';
import { ExclamationCircleOutlined, InfoCircleOutlined } from '@ant-design/icons';
import { getSportNameInVietnamese } from '@/utils/translateSport';

const { Title, Text } = Typography;
const { Option } = Select;

interface FieldGroupFormProps {
  open: boolean;
  onClose: () => void;
  onSave: (fieldGroup: FieldGroupFormData) => void;
  sport: Sport;
  allSports: Sport[];
  selectedSportIds?: number[]; // Optional parameter for pre-selected sports
}

const FieldGroupForm: React.FC<FieldGroupFormProps> = ({
  open,
  onClose,
  onSave,
  sport,
  allSports,
  selectedSportIds = [] // Default to empty array if not provided
}) => {
  const [form] = Form.useForm();
  const [selectedSports, setSelectedSports] = useState<number[]>([sport.id]);
  const [isMultiSport, setIsMultiSport] = useState<boolean>(false);
  const [fieldCount, setFieldCount] = useState<number>(1);
  const [namingMethod, setNamingMethod] = useState<'auto' | 'custom'>('auto');
  const [fieldPrefix, setFieldPrefix] = useState<string>(`Sân ${getSportNameInVietnamese(sport.name)}`);
  const [customNames, setCustomNames] = useState<string[]>([]);
  
  // Reset form when modal opens
  useEffect(() => {
    if (open) {
      // Reset states first
      // Handle which sport to initialize with
      const initialSportIds = selectedSportIds.length > 0 
        ? selectedSportIds 
        : (sport.id === 999 
          ? allSports.filter(s => s.id !== 999).slice(0, 2).map(s => s.id)
          : [sport.id]);
          
      setSelectedSports(initialSportIds);
      // Automatically set multi-sport flag based on sport type or multiple selection
      const isMultiSportField = sport.id === 999 || initialSportIds.length > 1;
      setIsMultiSport(isMultiSportField);
      setFieldCount(1);
      setNamingMethod('auto');
      
      // Set appropriate field prefix based on selected sport
      const prefixText = sport.id === 999 
        ? 'Đa năng' 
        : getSportNameInVietnamese(sport.name);
      setFieldPrefix(`Sân ${prefixText}`);
      setCustomNames([]);
      
      // Reset form with default values
      setTimeout(() => {
        // Get sport key for accessing mock data
        const sportKey = (sport.id === 999 ? 'football' : sport.name.toLowerCase()) as keyof typeof SURFACE_TYPES;
        
        // Get defaults from mock data
        const surfaceOptions = SURFACE_TYPES[sportKey] || SURFACE_TYPES.default;
        const dimensionOptions = DIMENSIONS[sportKey] || DIMENSIONS.default;
        const defaultPrice = DEFAULT_PRICING[sportKey as keyof typeof DEFAULT_PRICING] || DEFAULT_PRICING.default;
        
        // Kiểm tra xem có tồn tại các options và giá trị mặc định không
        const finalSurface = surfaceOptions.length > 0 ? surfaceOptions[0] : '';
        const finalDimension = dimensionOptions.length > 0 ? dimensionOptions[0] : '';
        
        // Reset form with initial values
        form.resetFields();
        
        // Create appropriate form name based on sport type and field count
        const sportName = sport.id === 999 
          ? 'Đa năng' 
          : getSportNameInVietnamese(sport.name);
        
        const autoGeneratedName = `Nhóm 1 sân ${sportName}`;
        
        form.setFieldsValue({
          name: autoGeneratedName,
          dimension: finalDimension,
          surface: finalSurface,
          basePrice: defaultPrice,
          numberOfPeaks: 1,
          sportIds: initialSportIds,
          fieldCount: 1,
          useCustomName: false,
        });
      }, 0);
    }
  }, [open, form, sport, allSports, selectedSportIds]);
  
  // Generate field names based on naming method and count
  const generateFieldNames = () => {
    if (namingMethod === 'auto') {
      return Array.from({ length: fieldCount }, (_, i) => `${fieldPrefix} ${i + 1}`);
    } else {
      return customNames.slice(0, fieldCount);
    }
  };
  
  // Handle field count change
  const handleFieldCountChange = (value: number | null) => {
    if (!value) return;
    
    setFieldCount(value);
    
    // Update field group name if auto naming is enabled
    const useCustomName = form.getFieldValue('useCustomName');
    if (!useCustomName) {
      const sportName = sport.id === 999 
        ? 'Đa năng' 
        : getSportNameInVietnamese(sport.name);
      form.setFieldsValue({
        name: `Nhóm ${value} sân ${sportName}`
      });
    }
    
    // Update custom names if needed
    if (namingMethod === 'custom') {
      const newNames = [...customNames];
      while (newNames.length < value) {
        newNames.push(`Sân ${newNames.length + 1}`);
      }
      setCustomNames(newNames);
    }
  };
  
  // Handle custom name change
  const handleCustomNameChange = (index: number, value: string) => {
    const newNames = [...customNames];
    newNames[index] = value;
    setCustomNames(newNames);
  };
  
  // Handle naming method change
  const handleNamingMethodChange = (method: 'auto' | 'custom') => {
    setNamingMethod(method);
    
    if (method === 'custom') {
      // Initialize custom names if switching to custom
      const initialNames = Array.from({ length: fieldCount }, (_, i) => 
        `${getSportNameInVietnamese(sport.name)} ${i + 1}`
      );
      setCustomNames(initialNames);
    }
  };
  
  // Handle sport selection
  const handleSportSelect = (values: number[]) => {
    setSelectedSports(values);
    form.setFieldsValue({ sportIds: values });
    
    // If values length is greater than 1, try to find a suitable composite group
    if (values.length > 1) {
      // Find sport objects for the selected ids
      const selectedSportObjects = values.map(id => 
        allSports.find(s => s.id === id)
      ).filter(Boolean) as Sport[];
      
      // Get sport names for lookup
      const selectedSportNames = selectedSportObjects.map(s => s.name.toLowerCase());
      
      // Try to find a compatible group that matches our selection
      const matchingGroup = COMPATIBLE_SPORT_GROUPS.find(group => {
        // Check if all selected sports are in this group
        return selectedSportNames.every(sport => group.sports.includes(sport));
      });
      
      if (matchingGroup) {
        // Found a matching group, use its recommendations
        if (matchingGroup.recommendedSurfaces && matchingGroup.recommendedSurfaces.length > 0) {
          form.setFieldsValue({ surface: matchingGroup.recommendedSurfaces[0] });
        }
        
        if (matchingGroup.recommendedDimensions && matchingGroup.recommendedDimensions.length > 0) {
          form.setFieldsValue({ dimension: matchingGroup.recommendedDimensions[0] });
        }
        
        // Update field prefix and group name
        setFieldPrefix(`Sân ${matchingGroup.name}`);
        
        // Only update name if not using custom name
        const useCustomName = form.getFieldValue('useCustomName');
        if (!useCustomName) {
          const fieldCount = form.getFieldValue('fieldCount') || 1;
          form.setFieldsValue({
            name: `Nhóm ${fieldCount} ${matchingGroup.name}`
          });
        }
      } else {
        // No exact match, just use a generic name
        const sportName = 'Đa năng';
        setFieldPrefix(`Sân ${sportName}`);
        
        // Only update name if not using custom name
        const useCustomName = form.getFieldValue('useCustomName');
        if (!useCustomName) {
          const fieldCount = form.getFieldValue('fieldCount') || 1;
          form.setFieldsValue({
            name: `Nhóm ${fieldCount} sân ${sportName}`
          });
        }
      }
    } else if (values.length === 1) {
      // Only one sport selected
      const selectedSport = allSports.find(s => s.id === values[0]);
      if (selectedSport) {
        const sportName = getSportNameInVietnamese(selectedSport.name);
        setFieldPrefix(`Sân ${sportName}`);
        
        // Only update name if not using custom name
        const useCustomName = form.getFieldValue('useCustomName');
        if (!useCustomName) {
          const fieldCount = form.getFieldValue('fieldCount') || 1;
          form.setFieldsValue({
            name: `Nhóm ${fieldCount} sân ${sportName}`
          });
        }
      }
    }
  };
  
  // Get surface options based on selected sports
  const getSurfaceOptions = () => {
    if (selectedSports.length === 0) return SURFACE_TYPES.default;
    
    // Find the first selected sport
    const selectedSport = allSports.find(s => s.id === selectedSports[0]);
    if (!selectedSport) return SURFACE_TYPES.default;
    
    // Get the sport key for accessing mock data
    const sportKey = selectedSport.name.toLowerCase() as keyof typeof SURFACE_TYPES;
    
    return SURFACE_TYPES[sportKey] || SURFACE_TYPES.default;
  };
  
  // Get dimension options based on selected sports
  const getDimensionOptions = () => {
    if (selectedSports.length === 0) return DIMENSIONS.default;
    
    // Find the first selected sport
    const selectedSport = allSports.find(s => s.id === selectedSports[0]);
    if (!selectedSport) return DIMENSIONS.default;
    
    // Get the sport key for accessing mock data
    const sportKey = selectedSport.name.toLowerCase() as keyof typeof DIMENSIONS;
    
    return DIMENSIONS[sportKey] || DIMENSIONS.default;
  };
  
  // Update the form values if the selected sport changes and options change
  useEffect(() => {
    // This effect should not be needed anymore as we use Form.Item with shouldUpdate
    // to handle the surface and dimension options
  }, [selectedSports, form]);
  
  // Handle form submission
  const handleSubmit = () => {
    form.validateFields().then(values => {
      // Generate field data based on naming method
      const fieldNames = generateFieldNames();
      const fieldsData = fieldNames.map((name, index) => ({ 
        id: `tmp-${index}`,
        name,
        status: 'active' as const
      }));
      
      // Prepare data for submission
      const fieldGroupData: FieldGroupFormData = {
        name: values.name,
        dimension: values.dimension,
        surface: values.surface,
        basePrice: values.basePrice,
        numberOfPeaks: values.numberOfPeaks || 1,
        peakStartTime1: values.peakTime1 ? values.peakTime1[0].format('HH:mm:ss') : '',
        peakEndTime1: values.peakTime1 ? values.peakTime1[1].format('HH:mm:ss') : '',
        priceIncrease1: values.priceIncrease1 || 0,
        peakStartTime2: values.peakTime2 ? values.peakTime2[0].format('HH:mm:ss') : '',
        peakEndTime2: values.peakTime2 ? values.peakTime2[1].format('HH:mm:ss') : '',
        priceIncrease2: values.priceIncrease2 || 0,
        peakStartTime3: values.peakTime3 ? values.peakTime3[0].format('HH:mm:ss') : '',
        peakEndTime3: values.peakTime3 ? values.peakTime3[1].format('HH:mm:ss') : '',
        priceIncrease3: values.priceIncrease3 || 0,
        sportIds: values.sportIds || [sport.id],
        fieldsData,
      };
      
      // Show confirmation modal
      Modal.confirm({
        title: 'Xác nhận tạo nhóm sân mới',
        icon: <ExclamationCircleOutlined />,
        content: (
          <div>
            <p>Bạn có chắc chắn muốn tạo nhóm sân mới với thông tin đã nhập?</p>
            <p style={{ marginTop: '10px' }}>
              <b>Lưu ý:</b> Việc tạo nhóm sân mới đồng nghĩa với việc bạn xác nhận các sân này có thực và thuộc quyền quản lý của cơ sở. Bạn chịu hoàn toàn trách nhiệm về tính xác thực của thông tin này.
            </p>
          </div>
        ),
        onOk() {
          onSave(fieldGroupData);
        },
        okText: 'Xác nhận',
        cancelText: 'Hủy',
      });
    });
  };
  
  return (
    <Modal
      title={<Title level={4}>Tạo nhóm sân mới</Title>}
      open={open}
      onCancel={onClose}
      onOk={handleSubmit}
      okText="Tạo nhóm sân"
      cancelText="Hủy"
      width={800}
      style={{ top: 20 }}
      styles={{ 
        body: { maxHeight: 'calc(100vh - 200px)', overflowY: 'auto' }
      }}
    >
      <Form.Provider>
        <Form
          form={form}
          layout="vertical"
          initialValues={{
            numberOfPeaks: 1,
            fieldCount: 1,
          }}
        >
          {/* Basic Information */}
          <Title level={5}>Thông tin cơ bản</Title>
          <Row gutter={16}>
            <Col span={12}>
              <Form.Item noStyle shouldUpdate>
                {({ getFieldValue }) => {
                  const useCustomName = getFieldValue('useCustomName');
                  
                  return (
                    <>
                      <Form.Item
                        label="Tên nhóm sân"
                        name="name"
                        rules={[{ required: true, message: 'Vui lòng nhập tên nhóm sân' }]}
                      >
                        <Input 
                          placeholder="Nhập tên nhóm sân" 
                          disabled={!useCustomName}
                        />
                      </Form.Item>
                      
                      <Form.Item
                        name="useCustomName"
                        valuePropName="checked"
                        initialValue={false}
                      >
                        <Checkbox 
                          onChange={(e) => {
                            // If turning off custom naming, regenerate the name
                            if (!e.target.checked) {
                              const fieldCount = form.getFieldValue('fieldCount') || 1;
                              const sportName = sport.id === 999 
                                ? 'Đa năng' 
                                : getSportNameInVietnamese(sport.name);
                              form.setFieldsValue({
                                name: `Nhóm ${fieldCount} sân ${sportName}`
                              });
                            }
                          }}
                        >
                          Tùy chỉnh tên nhóm sân
                        </Checkbox>
                      </Form.Item>
                    </>
                  );
                }}
              </Form.Item>
            </Col>
            
            <Col span={12}>
              <Form.Item
                label="Giá sân cơ bản"
                name="basePrice"
                rules={[{ required: true, message: 'Vui lòng nhập giá sân' }]}
              >
                <InputNumber
                  style={{ width: '100%' }}
                  addonAfter="VNĐ/giờ"
                  placeholder="Nhập giá sân cơ bản"
                  min={0}
                  max={999999999}
                  step={10000}
                  formatter={(value) => `${value}`.replace(/\B(?=(\d{3})+(?!\d))/g, '.')}
                  parser={(value: string | undefined) => {
                  if (!value) return 0;
                  return Number(value.replace(/\./g, ''));
                }}
                />
              </Form.Item>
            </Col>
          </Row>
          
          {/* Sport Type */}
          <Row gutter={16}>
            <Col span={24}>
              <Form.Item label="Loại hình thể thao">
                {isMultiSport ? (
                  <>
                    <div className="mb-2">
                      <Text>Sân đa năng (nhiều môn thể thao)</Text>
                    </div>
                    
                    {/* Recommended combinations */}
                    {sport.id === 999 && (
                      <div className="mb-4">
                        <Alert
                          type="info"
                          message={
                            <div>
                              <div className="font-medium mb-2">
                                <InfoCircleOutlined className="mr-2" />
                                Gợi ý các loại sân tổng hợp phổ biến
                              </div>
                              <div className="grid grid-cols-1 md:grid-cols-2 gap-2 mb-3">
                                {COMPATIBLE_SPORT_GROUPS.map(group => (
                                  <Card 
                                    key={group.id} 
                                    size="small" 
                                    className="cursor-pointer hover:shadow-md"
                                    onClick={() => {
                                      // Find sport IDs matching the sport names
                                      const sportIds = group.sports
                                        .map(sportName => {
                                          const matchingSport = allSports.find(
                                            s => s.name.toLowerCase() === sportName.toLowerCase()
                                          );
                                          return matchingSport?.id;
                                        })
                                        .filter(Boolean) as number[];
                                      
                                      if (sportIds.length > 0) {
                                        // Set the selected sports
                                        setSelectedSports(sportIds);
                                        form.setFieldsValue({ sportIds: sportIds });
                                        
                                        // Set recommended surface and dimension if available
                                        if (group.recommendedSurfaces && group.recommendedSurfaces.length > 0) {
                                          form.setFieldsValue({ surface: group.recommendedSurfaces[0] });
                                        }
                                        
                                        if (group.recommendedDimensions && group.recommendedDimensions.length > 0) {
                                          form.setFieldsValue({ dimension: group.recommendedDimensions[0] });
                                        }
                                        
                                        // Update the field prefix based on group name
                                        setFieldPrefix(`Sân ${group.name}`);
                                        
                                        // Update the form name to include the group name
                                        const fieldCount = form.getFieldValue('fieldCount') || 1;
                                        form.setFieldsValue({
                                          name: `Nhóm ${fieldCount} ${group.name}`
                                        });
                                      }
                                    }}
                                  >
                                    <div className="font-medium text-sm">{group.name}</div>
                                    <div className="text-xs text-gray-500">{group.description}</div>
                                    <div className="flex flex-wrap gap-1 mt-1">
                                      {group.sports.map((sportName, idx) => {
                                        const matchingSport = allSports.find(
                                          s => s.name.toLowerCase() === sportName.toLowerCase()
                                        );
                                        return matchingSport ? (
                                          <Tag key={idx} color="blue">
                                            {getSportNameInVietnamese(matchingSport.name)}
                                          </Tag>
                                        ) : null;
                                      })}
                                    </div>
                                    {group.recommendedSurfaces && group.recommendedSurfaces.length > 0 && (
                                      <div className="text-xs mt-2">
                                        <span className="text-gray-500">Mặt sân: </span>
                                        {group.recommendedSurfaces[0]}
                                      </div>
                                    )}
                                    {group.recommendedDimensions && group.recommendedDimensions.length > 0 && (
                                      <div className="text-xs">
                                        <span className="text-gray-500">Kích thước: </span>
                                        {group.recommendedDimensions[0]}
                                      </div>
                                    )}
                                  </Card>
                                ))}
                              </div>
                              <Text type="secondary" className="text-xs">Nhấp vào một gợi ý để chọn nhanh cấu hình sân tổng hợp</Text>
                            </div>
                          }
                        />
                      </div>
                    )}
                    
                    <Form.Item 
                      name="sportIds"
                      rules={[{ required: true, message: 'Vui lòng chọn ít nhất một loại hình thể thao' }]}
                      noStyle
                    >
                      <Select
                        mode="multiple"
                        placeholder="Chọn loại hình thể thao"
                        onChange={handleSportSelect}
                        style={{ width: '100%' }}
                        disabled={sport.id === 999} // Disable editing if this is a Composite field
                      >
                        {allSports
                          .filter(s => s.id !== 999) // Remove Composite from options
                          .map(sport => (
                            <Option key={sport.id} value={sport.id}>
                              {getSportNameInVietnamese(sport.name)}
                            </Option>
                          ))
                        }
                      </Select>
                    </Form.Item>
                    
                    {sport.id === 999 && (
                      <div className="mt-2">
                        <Text type="secondary">
                          Các loại hình thể thao đã chọn cho sân đa năng:
                        </Text>
                        <div className="flex flex-wrap gap-1 mt-1">
                          {selectedSports.map(sportId => {
                            const sportObj = allSports.find(s => s.id === sportId);
                            return sportObj ? (
                              <Tag key={sportId} color="blue">
                                {getSportNameInVietnamese(sportObj.name)}
                              </Tag>
                            ) : null;
                          })}
                        </div>
                      </div>
                    )}
                  </>
                ) : (
                  <div>
                    <Text strong>{getSportNameInVietnamese(sport.name)}</Text>
                  </div>
                )}
              </Form.Item>
            </Col>
          </Row>
          
          {/* Surface and Dimensions */}
          <Row gutter={16}>
            <Col span={12}>
              <Form.Item noStyle shouldUpdate={(prevValues, currentValues) => 
                prevValues.sportIds !== currentValues.sportIds
              }>
                {() => (
                  <Form.Item
                    label="Mặt sân"
                    name="surface"
                    rules={[{ required: true, message: 'Vui lòng chọn mặt sân' }]}
                  >
                    <Select placeholder="Chọn mặt sân">
                      {getSurfaceOptions().map((surface, index) => (
                        <Option key={index} value={surface}>
                          {surface}
                        </Option>
                      ))}
                    </Select>
                  </Form.Item>
                )}
              </Form.Item>
            </Col>
            
            <Col span={12}>
              <Form.Item noStyle shouldUpdate={(prevValues, currentValues) => 
                prevValues.sportIds !== currentValues.sportIds
              }>
                {() => (
                  <Form.Item
                    label="Kích thước"
                    name="dimension"
                    rules={[{ required: true, message: 'Vui lòng chọn kích thước sân' }]}
                  >
                    <Select placeholder="Chọn kích thước sân">
                      {getDimensionOptions().map((dimension, index) => (
                        <Option key={index} value={dimension}>
                          {dimension}
                        </Option>
                      ))}
                    </Select>
                  </Form.Item>
                )}
              </Form.Item>
            </Col>
          </Row>
          
          <Divider />
          
          {/* Peak Hours */}
          <Title level={5}>Giờ cao điểm</Title>
          <Form.Item 
            name="numberOfPeaks" 
            label="Số lượng khung giờ cao điểm"
          >
            <Select>
              <Option value={1}>1 khung giờ</Option>
              <Option value={2}>2 khung giờ</Option>
              <Option value={3}>3 khung giờ</Option>
            </Select>
          </Form.Item>
          
          {/* Peak Time 1 */}
          <Row gutter={16}>
            <Col span={16}>
              <Form.Item label="Giờ cao điểm 1" name="peakTime1">
                <TimePicker.RangePicker 
                  format="HH:mm" 
                  style={{ width: '100%' }}
                  placeholder={['Giờ bắt đầu', 'Giờ kết thúc']}
                />
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item label="Tăng giá" name="priceIncrease1">
                <InputNumber
                  style={{ width: '100%' }}
                  addonAfter="VNĐ/giờ"
                  min={0}
                  max={999999999}
                  step={10000}
                  formatter={(value) => `${value}`.replace(/\B(?=(\d{3})+(?!\d))/g, '.')}
                parser={(value: string | undefined) => {
                  if (!value) return 0;
                  return Number(value.replace(/\./g, ''));
                }}
                />
              </Form.Item>
            </Col>
          </Row>
          
          {/* Peak Time 2 & 3 - Conditional rendering */}
          <Form.Item noStyle shouldUpdate={(prevValues, currentValues) => 
            prevValues.numberOfPeaks !== currentValues.numberOfPeaks
          }>
            {({ getFieldValue }) => {
              const numberOfPeaks = getFieldValue('numberOfPeaks');
              return (
                <>
                  {/* Peak Time 2 - Conditional rendering */}
                  {numberOfPeaks >= 2 && (
                    <Row gutter={16}>
                      <Col span={16}>
                        <Form.Item label="Giờ cao điểm 2" name="peakTime2">
                          <TimePicker.RangePicker 
                            format="HH:mm" 
                            style={{ width: '100%' }}
                            placeholder={['Giờ bắt đầu', 'Giờ kết thúc']}
                          />
                        </Form.Item>
                      </Col>
                      <Col span={8}>
                        <Form.Item label="Tăng giá" name="priceIncrease2">
                          <InputNumber
                            style={{ width: '100%' }}
                            addonAfter="VNĐ"
                            min={0}
                            max={999999999}
                            step={10000}
                            formatter={(value) => `${value}`.replace(/\B(?=(\d{3})+(?!\d))/g, '.')}
                parser={(value: string | undefined) => {
                  if (!value) return 0;
                  return Number(value.replace(/\./g, ''));
                }}
                          />
                        </Form.Item>
                      </Col>
                    </Row>
                  )}
                  
                  {/* Peak Time 3 - Conditional rendering */}
                  {numberOfPeaks >= 3 && (
                    <Row gutter={16}>
                      <Col span={16}>
                        <Form.Item label="Giờ cao điểm 3" name="peakTime3">
                          <TimePicker.RangePicker 
                            format="HH:mm" 
                            style={{ width: '100%' }}
                            placeholder={['Giờ bắt đầu', 'Giờ kết thúc']}
                          />
                        </Form.Item>
                      </Col>
                      <Col span={8}>
                        <Form.Item label="Tăng giá" name="priceIncrease3">
                          <InputNumber
                            style={{ width: '100%' }}
                            addonAfter="VNĐ"
                            min={0}
                            max={999999999}
                            step={10000}
                            formatter={(value) => `${value}`.replace(/\B(?=(\d{3})+(?!\d))/g, '.')}
                parser={(value: string | undefined) => {
                  if (!value) return 0;
                  return Number(value.replace(/\./g, ''));
                }}
                          />
                        </Form.Item>
                      </Col>
                    </Row>
                  )}
                </>
              );
            }}
          </Form.Item>
          
          <Divider />
          
          {/* Fields */}
          <Title level={5}>Thông tin sân</Title>
          <Row gutter={16}>
            <Col span={12}>
              <Form.Item 
                label="Số lượng sân" 
                name="fieldCount"
                rules={[{ required: true, message: 'Vui lòng nhập số lượng sân' }]}
              >
                <InputNumber 
                  min={1} 
                  max={20} 
                  style={{ width: '100%' }} 
                  onChange={handleFieldCountChange}
                />
              </Form.Item>
            </Col>
            
            <Col span={12}>
              <Form.Item noStyle shouldUpdate={(prevValues, currentValues) => 
                prevValues.useCustomName !== currentValues.useCustomName || 
                prevValues.fieldCount !== currentValues.fieldCount
              }>
                {({ getFieldValue }) => {
                  const useCustomName = getFieldValue('useCustomName');
                  const fieldCount = getFieldValue('fieldCount') || 1;
                  
                  // Auto-update group name if not custom
                  if (!useCustomName && form.getFieldValue('name')) {
                    const sportName = sport.id === 999 
                      ? 'Đa năng' 
                      : getSportNameInVietnamese(sport.name);
                    
                    setTimeout(() => {
                      form.setFieldsValue({
                        name: `Nhóm ${fieldCount} sân ${sportName}`
                      });
                    }, 0);
                  }
                  
                  return (
                    <Form.Item label="Phương thức đặt tên">
                      <Select
                        value={namingMethod}
                        onChange={handleNamingMethodChange}
                        style={{ width: '100%' }}
                      >
                        <Option value="auto">Tự động</Option>
                        <Option value="custom">Tùy chỉnh</Option>
                      </Select>
                    </Form.Item>
                  );
                }}
              </Form.Item>
            </Col>
          </Row>
          
          {/* Auto naming và Custom naming */}
          <Form.Item noStyle shouldUpdate={(prevValues, currentValues) =>
            prevValues.fieldCount !== currentValues.fieldCount
          }>
            {({ getFieldValue }) => {
              // Get field count from form instead of using the state directly
              const currentFieldCount = getFieldValue('fieldCount') || 1;
              
              return (
                <>
                  {/* Auto naming */}
                  {namingMethod === 'auto' && (
                    <Form.Item label="Tiền tố tên sân">
                      <Input 
                        value={fieldPrefix}
                        onChange={(e) => setFieldPrefix(e.target.value)}
                        placeholder="Nhập tiền tố cho tên sân (VD: Sân, Field)"
                      />
                      <Text type="secondary">
                        Tên sân sẽ được đặt tự động theo mẫu: {fieldPrefix} 1, {fieldPrefix} 2, ...
                      </Text>
                    </Form.Item>
                  )}
                  
                  {/* Custom naming */}
                  {namingMethod === 'custom' && (
                    <Form.Item label="Tên tùy chỉnh cho từng sân">
                      <div className="grid grid-cols-2 gap-2">
                        {Array.from({ length: currentFieldCount }).map((_, index) => (
                          <Input 
                            key={index}
                            value={customNames[index] || ''}
                            onChange={(e) => handleCustomNameChange(index, e.target.value)}
                            placeholder={`Tên sân ${index + 1}`}
                            className="mb-2"
                          />
                        ))}
                      </div>
                    </Form.Item>
                  )}
                </>
              );
            }}
          </Form.Item>
          
          {/* Preview */}
          <Card 
            title="Xem trước tên sân" 
            size="small" 
            className="mb-4"
            styles={{ body: { maxHeight: '150px', overflowY: 'auto' } }}
          >
            <div className="flex flex-wrap gap-2">
              {generateFieldNames().map((name, i) => (
                <Tag key={i} color="blue">{name}</Tag>
              ))}
            </div>
          </Card>
        </Form>
      </Form.Provider>
    </Modal>
  );
};

export default FieldGroupForm; 