export const ICONS = {
  DASHBOARD: new URL('@/assets/icons/dashboard.png', import.meta.url).href,
  USERS: new URL('@/assets/icons/users.png', import.meta.url).href,
  APPROVALS: new URL('@/assets/icons/approve.png', import.meta.url).href,
  FACILITIES: new URL('@/assets/icons/factory.png', import.meta.url).href,
  FIELDS: new URL('@/assets/icons/field.png', import.meta.url).href,
  SERVICES: new URL('@/assets/icons/services.png', import.meta.url).href,
  VOUCHERS: new URL('@/assets/icons/voucher.png', import.meta.url).href,
  EVENTS: new URL('@/assets/icons/event.png', import.meta.url).href,
  REVIEWS: new URL('@/assets/icons/review.png', import.meta.url).href,
  SUPPORTS: new URL('@/assets/icons/support.png', import.meta.url).href,
  REPORTS: new URL('@/assets/icons/report.png', import.meta.url).href,
  SETTINGS: new URL('@/assets/icons/settings.png', import.meta.url).href,
  LOGOUT: new URL('@/assets/icons/logout.png', import.meta.url).href,

  DASHBOARD_ACTIVE: new URL('@/assets/icons/dashboard-active.png', import.meta.url).href,
  USERS_ACTIVE: new URL('@/assets/icons/users.png', import.meta.url).href,
  APPROVALS_ACTIVE: new URL('@/assets/icons/approve.png', import.meta.url).href,
  FACILITIES_ACTIVE: new URL('@/assets/icons/factory.png', import.meta.url).href,
  FIELDS_ACTIVE: new URL('@/assets/icons/field.png', import.meta.url).href,
  SERVICES_ACTIVE: new URL('@/assets/icons/services.png', import.meta.url).href,
  VOUCHERS_ACTIVE: new URL('@/assets/icons/voucher.png', import.meta.url).href,
  EVENTS_ACTIVE: new URL('@/assets/icons/event.png', import.meta.url).href,
  REVIEWS_ACTIVE: new URL('@/assets/icons/review.png', import.meta.url).href,
  SUPPORTS_ACTIVE: new URL('@/assets/icons/support.png', import.meta.url).href,
  REPORTS_ACTIVE: new URL('@/assets/icons/report.png', import.meta.url).href,
  SETTINGS_ACTIVE: new URL('@/assets/icons/settings.png', import.meta.url).href,
  LOGOUT_ACTIVE: new URL('@/assets/icons/logout.png', import.meta.url).href,
} as const;
